In [1]:
import tensorflow as tf

/home/mi/zpz/anaconda3/envs/tf_2.0_gpu/lib/python3.7/site-packages/scipy/__init__.py:140: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.16.4)
  UserWarning)


In [2]:
tf.__version__


'2.0.0'

In [3]:
tf.executing_eagerly()  #自动处于eager模式

True

x = [[2,]]

In [4]:
x = [[2,]]


In [5]:
m = tf.matmul(x,x)

2021-11-26 13:31:40.670221: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-11-26 13:31:40.670290: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)
2021-11-26 13:31:40.670355: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (mi-HP-ProDesk-680-G6-PCI-Microtower-PC): /proc/driver/nvidia/version does not exist
2021-11-26 13:31:40.670891: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-11-26 13:31:40.704123: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2899885000 Hz
2021-11-26 13:31:40.704635: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5588f2ec9730 executing computations on platfo

In [6]:
m

<tf.Tensor: id=2, shape=(1, 1), dtype=int32, numpy=array([[4]], dtype=int32)>

In [7]:
print(m)

tf.Tensor([[4]], shape=(1, 1), dtype=int32)


In [8]:
m.numpy()

array([[4]], dtype=int32)

In [9]:
a =tf.constant([[1,2],[3,4]])

In [10]:
a

<tf.Tensor: id=3, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [11]:
a.numpy()

array([[1, 2],
       [3, 4]], dtype=int32)

In [12]:
b = tf.add(a,1)

In [13]:
b

<tf.Tensor: id=5, shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [14]:
c = tf.multiply(a,b)  #eager模式直接得到结果

In [15]:
c

<tf.Tensor: id=6, shape=(2, 2), dtype=int32, numpy=
array([[ 2,  6],
       [12, 20]], dtype=int32)>

In [16]:
num = tf.convert_to_tensor(10)

In [17]:
num

<tf.Tensor: id=7, shape=(), dtype=int32, numpy=10>

In [18]:
for i in range(num.numpy()):
     i = tf.constant(i)
     if int(i%2) == 0:
        print("even")

even
even
even
even
even


In [19]:
v = tf.Variable(0.0)

In [20]:
v + 1

<tf.Tensor: id=48, shape=(), dtype=float32, numpy=1.0>

In [21]:
(v + 1).numpy()

1.0

In [22]:
v

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.0>

In [23]:
v.assign(5)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=5.0>

In [24]:
v.read_value()

<tf.Tensor: id=55, shape=(), dtype=float32, numpy=5.0>

In [25]:
w = tf.Variable([[1.0]])
with tf.GradientTape() as t :
    loss = w*w

In [26]:
grad = t.gradient(loss,w) #自动求解微分计算  变量跟踪  

In [27]:
grad

<tf.Tensor: id=71, shape=(1, 1), dtype=float32, numpy=array([[2.]], dtype=float32)>

In [28]:
w = tf.constant([[3.0]])   #计算梯度 都是float类型
with tf.GradientTape() as t :
    t.watch(w)
    loss = w*w

In [29]:
grad = t.gradient(loss,w)

In [30]:
grad

<tf.Tensor: id=79, shape=(1, 1), dtype=float32, numpy=array([[6.]], dtype=float32)>

In [101]:
(train_image,train_labels),(test_image,test_labels) = tf.keras.datasets.mnist.load_data()

In [102]:
train_image.shape

(60000, 28, 28)

In [103]:
train_image = tf.expand_dims(train_image,-1)

In [104]:
test_image = tf.expand_dims(test_image,-1)

In [105]:
train_image.shape   #扩大维度

TensorShape([60000, 28, 28, 1])

In [106]:
test_image.shape

TensorShape([10000, 28, 28, 1])

In [107]:
train_image = tf.cast(train_image/255,tf.float32) #计算梯度 都是float类型

In [108]:
test_image = tf.cast(test_image/255,tf.float32) #计算梯度 都是float类型

In [109]:
train_labels = tf.cast(train_labels,tf.int64)

In [110]:
test_labels = tf.cast(test_labels,tf.int64)

In [111]:
dataset = tf.data.Dataset.from_tensor_slices((train_image,train_labels))

In [112]:
test_dataset = tf.data.Dataset.from_tensor_slices((test_image,test_labels))

In [113]:
dataset

<TensorSliceDataset shapes: ((28, 28, 1), ()), types: (tf.float32, tf.int64)>

In [114]:
dataset = dataset.shuffle(10000).batch(32)  #混洗 和 批次化 

In [115]:
test_dataset = test_dataset.batch(32)

In [116]:
dataset

<BatchDataset shapes: ((None, 28, 28, 1), (None,)), types: (tf.float32, tf.int64)>

In [117]:
model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(16,[3,3],activation="relu",input_shape=(None,None,1)), #任意形状
    tf.keras.layers.Conv2D(16,[3,3],activation="relu"),
    tf.keras.layers.GlobalMaxPooling2D(),
    tf.keras.layers.Dense(10)
    
    
])

In [118]:
#自定义循环 不需要编译
optimizer = tf.keras.optimizers.Adam()

In [119]:
loss_func = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [120]:
features,labels = next(iter(dataset)) #可迭代

In [121]:
features.shape   #验证刚才分批次的结果

TensorShape([32, 28, 28, 1])

In [122]:
labels.shape

TensorShape([32])

In [123]:
predictions = model(features) #模型直接调用  内置__Call__

In [124]:
predictions.shape   #32 个像10 的结果

TensorShape([32, 10])

In [125]:
tf.argmax(predictions,axis=1)  #预测结果 找出概率最大值

<tf.Tensor: id=84745, shape=(32,), dtype=int64, numpy=
array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7])>

In [126]:
labels    #实际结果

<tf.Tensor: id=84727, shape=(32,), dtype=int64, numpy=
array([7, 8, 6, 3, 9, 4, 1, 9, 6, 0, 2, 8, 8, 0, 9, 8, 4, 6, 8, 0, 1, 9,
       1, 5, 1, 3, 6, 9, 3, 1, 8, 0])>

In [127]:
#定义损失
def loss(model,x,y):
    y_ = model(x)
    return loss_func(y,y_)  #记录交叉商损失

In [128]:
train_loss = tf.keras.metrics.Mean("train_loss")
train_accuracy = tf.keras.metrics.SparseCategoricalAccuracy("train_accuracy")


test_loss = tf.keras.metrics.Mean("test_loss")
test_accuracy = tf.keras.metrics.SparseCategoricalAccuracy("test_accuracy")


In [129]:
#定义单步训练  计算损失函数
def train_step(model,images,labels):
    with tf.GradientTape() as t :
        pred = model(images)
        loss_step = loss_func(labels,pred) 
    grads = t.gradient(loss_step,model.trainable_variables)
    optimizer.apply_gradients(zip(grads,model.trainable_variables)) #优化函数的应用
    train_loss(loss_step)  #自动求值  得到平均
    train_accuracy(labels,pred)

In [130]:
def test_step(model,images,labels):
   
    pred = model(images)
    loss_step = loss_func(labels,pred) 

    test_loss(loss_step)  #自动求值  得到平均
    test_accuracy(labels,pred)

In [ ]:
def train():  #这就是fit内部函数实现机理
    for epoch in range(10):
        for (batch,(images,labels)) in enumerate(dataset):  #开始迭代每一个数据
            train_step(model,images,labels)
        print("Epoch{} loss is {},accuracy is {}".format(epoch,
                                                         train_loss.result(),
                                                         train_accuracy.result()
                                                        ))
        for (batch,(images,labels)) in enumerate(test_dataset):  #每训练一轮  在验证集测试一次
            test_step(model,images,labels)
        print("Epoch{} test_loss is {},tes_accuracy is {}".format(epoch,
                                                         test_loss.result(),
                                                         test_accuracy.result()
                                                        ))
        
        train_loss.reset_states()#重置变量 避免一次二次bacth相加
        train_accuracy.reset_states()
        test_loss.reset_states()#重置变量 避免一次二次bacth相加
        test_accuracy.reset_states()

In [ ]:
train()

In [133]:
tf.keras.metrics 汇总

SyntaxError: invalid syntax (1342954224.py, line 1)

In [44]:
m = tf.keras.metrics.Mean("acc")  #均值标准  这是一个对象 可看下面都是直接调用的

In [45]:
m(10)

<tf.Tensor: id=2137896, shape=(), dtype=float32, numpy=10.0>

In [46]:
m(20)

<tf.Tensor: id=2137905, shape=(), dtype=float32, numpy=15.0>

In [47]:
m.result()  #10 和20的均值是15

<tf.Tensor: id=2137908, shape=(), dtype=float32, numpy=15.0>

In [48]:
m.result().numpy()

15.0

In [49]:
m([30,40])

<tf.Tensor: id=2137920, shape=(), dtype=float32, numpy=25.0>

In [50]:
m.result().numpy()

25.0

In [51]:
m.reset_states()  #重置对象变量

In [52]:
m(1)

<tf.Tensor: id=2137934, shape=(), dtype=float32, numpy=1.0>

In [53]:
m(2)

<tf.Tensor: id=2137943, shape=(), dtype=float32, numpy=1.5>

In [54]:
m.result().numpy()

1.5

In [57]:
a = tf.keras.metrics.SparseCategoricalAccuracy("acc")

In [59]:
a(labels,model(features))   #这个函数不用你手动取选择最大值  自动给你求出最大值  然后计算正确率

<tf.Tensor: id=2137989, shape=(), dtype=float32, numpy=0.84375>